services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    working_dir: /code
    volumes:
      - ./:/code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:8-fpm
    working_dir: /code
    volumes:
      - ./:/code
  #database:
    #image: mariadb:10.3.39
    #environment:
      #- name=value
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=crm
      - POSTGRES_PASSWORD=!ChangeMe!
      - POSTGRES_USER=postgres
    volumes:
      - db_data:/var/lib/postgresql/data:rw

volumes:
  db_data:
